"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import type{ReactNode}from"react";
import{FormEvent,useEffect,useState}from"react";
import{SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL}from"@/lib/leaflets";
const items=[["/admin","Visão geral"],["/admin/personalizacao","Personalização"],["/admin/campanhas","Campanhas"],["/admin/revistas","Revistas"],["/admin/folheteria","Folheteria"],["/admin/lojas","Lojas"],["/admin/midias","Biblioteca de mídia"],["/admin/usuarios","Usuários"],["/admin/configuracoes","Configurações"]]as const;
type Member={name:string|null;email:string;role:"admin"|"editor";status:"pending"|"approved"|"rejected"};
export function AdminShell({children}:{children:ReactNode}){const pathname=usePathname();const[token,setToken]=useState<string|null>(null);const[member,setMember]=useState<Member|null>(null);const[ready,setReady]=useState(false);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[requestMode,setRequestMode]=useState(false);const[mobileOpen,setMobileOpen]=useState(false);
async function loadMember(t:string){const user=await getUser(t);const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/cms_member_for_user`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({p_user_id:user.id})});if(!r.ok)return null;const rows=await r.json();return rows[0]??null}
async function getUser(t:string){const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error("Sessão inválida");return r.json()}
useEffect(()=>{(async()=>{const t=sessionStorage.getItem("coopercica_admin_token");if(t)try{const m=await loadMember(t);if(m?.status==="approved"){setToken(t);setMember(m)}else sessionStorage.removeItem("coopercica_admin_token")}catch{sessionStorage.removeItem("coopercica_admin_token")}setReady(true)})()},[]);
async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const fd=new FormData(e.currentTarget);const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email:fd.get("email"),password:fd.get("password")})});const j=await r.json();if(!r.ok){setError("E-mail ou senha inválidos.");setLoading(false);return}const m=await loadMember(j.access_token);if(!m||m.status!=="approved"){setError(m?.status==="rejected"?"Seu acesso ao CMS não foi aprovado.":"Sua solicitação ainda está aguardando aprovação.");setLoading(false);return}sessionStorage.setItem("coopercica_admin_token",j.access_token);setToken(j.access_token);setMember(m);setLoading(false)}
async function requestAccess(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const fd=new FormData(e.currentTarget);const email=String(fd.get("email")||"").trim().toLowerCase();if(!email.endsWith("@coopercica.com.br")){setError("Use seu e-mail corporativo @coopercica.com.br.");setLoading(false);return}const r=await fetch(`${SUPABASE_URL}/auth/v1/signup`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email,password:fd.get("password"),data:{name:fd.get("name")}})});const j=await r.json();setLoading(false);if(!r.ok){setError(j.msg||j.error_description||"Não foi possível solicitar o acesso.");return}setRequestMode(false);setError("Solicitação enviada. Após a aprovação, use seu e-mail e senha para entrar.")}
function logout(){sessionStorage.removeItem("coopercica_admin_token");setMobileOpen(false);setToken(null);setMember(null)}
useEffect(()=>{setMobileOpen(false)},[pathname]);
useEffect(()=>{document.body.style.overflow=mobileOpen?"hidden":"";return()=>{document.body.style.overflow=""}},[mobileOpen]);
if(!ready)return null;
if(!token)return <div className="cms-auth"><section className="cms-auth-card"><div className="cms-auth-brand"><Link href="/">Coopercica</Link><span>CMS</span></div><div className="cms-auth-copy"><span className="eyebrow">{requestMode?"Solicitar acesso":"Conteúdo digital"}</span><h1>{requestMode?"Acesse o CMS da Coopercica":"Gerencie o site em um só lugar."}</h1><p>{requestMode?"Crie sua solicitação. Um administrador precisa aprovar o acesso antes do primeiro login.":"Entre para administrar campanhas, folhetos, revistas, lojas e arquivos do site."}</p></div><form onSubmit={requestMode?requestAccess:login} className="cms-auth-form">{requestMode?<label>Nome<input name="name" required autoComplete="name"/></label>:null}<label>E-mail<input name="email" type="email" required autoComplete="email"/></label><label>Senha<input name="password" type="password" minLength={6} required autoComplete={requestMode?"new-password":"current-password"}/></label>{error?<div className="cms-auth-message">{error}</div>:null}<button className="button" disabled={loading}>{loading?"Aguarde...":requestMode?"Solicitar acesso":"Entrar no CMS"}</button></form><button className="cms-auth-switch" type="button" onClick={()=>{setRequestMode(v=>!v);setError("")}}>{requestMode?"Já tenho acesso":"Ainda não tenho acesso · Solicitar"}</button><Link className="cms-auth-back" href="/">← Voltar ao site</Link></section></div>;
const nav=items.filter(([href])=>href!=="/admin/usuarios"||member?.role==="admin");
return <div className="admin-shell">
<header className="cms-mobile-header"><Link href="/admin" className="cms-mobile-brand"><strong>Coopercica</strong><span>CMS</span></Link><button className="cms-menu-button" type="button" aria-label="Abrir menu do CMS" aria-expanded={mobileOpen} onClick={()=>setMobileOpen(true)}><span/><span/><span/></button></header>
{mobileOpen?<button className="cms-drawer-backdrop" aria-label="Fechar menu" onClick={()=>setMobileOpen(false)}/>:null}
<aside className={mobileOpen?"cms-drawer-open":""}><div className="cms-aside-head"><div><Link className="admin-brand" href="/admin">Coopercica</Link><span className="admin-kicker">CMS · Conteúdo Digital</span></div><button className="cms-drawer-close" type="button" aria-label="Fechar menu" onClick={()=>setMobileOpen(false)}>×</button></div><nav>{nav.map(([href,label])=>{const active=href==="/admin"?pathname===href:pathname.startsWith(href);return <Link href={href} key={href} aria-current={active?"page":undefined}>{label}</Link>})}</nav><div className="cms-user"><strong>{member?.name||member?.email}</strong><small>{member?.role==="admin"?"Administrador":"Editor"}</small><button onClick={logout}>Sair do CMS</button></div></aside>
<main>{children}</main>
</div>}