"use client";
import Link from"next/link";import type{ReactNode}from"react";import{FormEvent,useEffect,useState}from"react";import{SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL}from"@/lib/leaflets";
const items=[["/admin","Visão geral"],["/admin/campanhas","Campanhas"],["/admin/revistas","Revistas"],["/admin/folheteria","Folheteria Digital"],["/admin/lojas","Lojas"],["/admin/analytics","Analytics"],["/admin/configuracoes","Configurações"]]as const;
export function AdminShell({children}:{children:ReactNode}){const[token,setToken]=useState<string|null>(null);const[ready,setReady]=useState(false);const[error,setError]=useState("");const[loading,setLoading]=useState(false);
useEffect(()=>{setToken(sessionStorage.getItem("coopercica_admin_token"));setReady(true)},[]);
async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const fd=new FormData(e.currentTarget);const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email:fd.get("email"),password:fd.get("password")})});const j=await r.json();setLoading(false);if(!r.ok){setError("E-mail ou senha inválidos.");return}sessionStorage.setItem("coopercica_admin_token",j.access_token);setToken(j.access_token)}
if(!ready)return null;
if(!token)return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:"32px 20px",background:"#f4f8f3"}}><section style={{width:"min(100%,460px)",background:"#fff",border:"1px solid rgba(21,78,40,.09)",borderRadius:28,padding:"42px 40px",boxShadow:"0 24px 70px rgba(24,67,35,.10)"}}><div style={{marginBottom:34}}><Link href="/" style={{display:"inline-block",fontSize:25,fontWeight:900,color:"#164d29",textDecoration:"none",letterSpacing:"-.04em"}}>Coopercica</Link><span style={{display:"block",marginTop:7,fontSize:11,fontWeight:800,letterSpacing:".16em",textTransform:"uppercase",color:"#68bd39"}}>Painel de Marketing</span></div><div style={{marginBottom:28}}><h1 style={{margin:"0 0 10px",fontSize:"clamp(2rem,4vw,2.65rem)",lineHeight:1,letterSpacing:"-.045em",color:"#233c31"}}>Bem-vindo</h1><p style={{margin:0,color:"#6c7c73",lineHeight:1.55}}>Entre com sua conta para acessar o painel administrativo.</p></div><form onSubmit={login} style={{display:"grid",gap:18}}><label style={{display:"grid",gap:8,fontSize:13,fontWeight:800,color:"#164d29"}}>E-mail<input name="email" type="email" autoComplete="email" required style={{width:"100%",height:52,border:"1px solid #d7e4d8",borderRadius:14,padding:"0 16px",fontSize:16,outline:"none",background:"#f9fbf8"}}/></label><label style={{display:"grid",gap:8,fontSize:13,fontWeight:800,color:"#164d29"}}>Senha<input name="password" type="password" autoComplete="current-password" required style={{width:"100%",height:52,border:"1px solid #d7e4d8",borderRadius:14,padding:"0 16px",fontSize:16,outline:"none",background:"#f9fbf8"}}/></label>{error?<p style={{margin:0,padding:"11px 13px",borderRadius:12,background:"#fff3f1",color:"#b6382f",fontSize:13}}>{error}</p>:null}<button type="submit" disabled={loading} style={{height:54,border:0,borderRadius:999,background:"#174f28",color:"#fff",fontSize:16,fontWeight:800,cursor:"pointer",marginTop:4}}>{loading?"Entrando...":"Entrar"}</button></form><Link href="/" style={{display:"block",marginTop:25,textAlign:"center",fontSize:13,color:"#6c7c73",textDecoration:"none"}}>← Voltar ao site</Link></section></div>;
return <div className="admin-shell"><aside><Link className="admin-brand" href="/">Coopercica</Link><span className="admin-kicker">Painel de Marketing</span><nav>{items.map(([href,label])=><Link href={href} key={href}>{label}</Link>)}</nav><Link className="admin-back" href="/">← Voltar ao site</Link></aside><main>{children}</main></div>}
