"use client";
import{useCallback,useEffect,useState}from"react";import{SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL}from"@/lib/leaflets";
type Kind="campaign"|"leaflet"|"magazine"|"store";
type Row={id:string;title:string;meta:string;status:string;image?:string|null};
const config:Record<Kind,{table:string;select:string;order:string}>={campaign:{table:"site_campaigns",select:"id,title,active,starts_at,ends_at,desktop_image_url,sort_order",order:"sort_order.asc"},leaflet:{table:"digital_leaflets",select:"id,name,status,starts_at,ends_at,cover_url",order:"created_at.desc"},magazine:{table:"site_magazines",select:"id,title,edition,active,published_at,cover_url",order:"published_at.desc"},store:{table:"site_stores",select:"id,name,city,neighborhood,active,store_number,image_url",order:"store_number.asc"}};
export function ContentList({kind,title}:{kind:Kind;title:string}){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
const load=useCallback(async()=>{const t=sessionStorage.getItem("coopercica_admin_token");if(!t)return;setLoading(true);const c=config[kind];const r=await fetch(`${SUPABASE_URL}/rest/v1/${c.table}?select=${encodeURIComponent(c.select)}&order=${c.order}`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${t}`}});const data=r.ok?await r.json():[];setRows(data.map((x:any)=>kind==="campaign"?{id:x.id,title:x.title,meta:`Ordem ${x.sort_order}`,status:x.active?"Publicado":"Inativo",image:x.desktop_image_url}:kind==="leaflet"?{id:x.id,title:x.name,meta:`${x.starts_at} → ${x.ends_at}`,status:x.status==="published"?"Publicado":"Rascunho",image:x.cover_url}:kind==="magazine"?{id:x.id,title:x.title,meta:`${x.edition} · ${x.published_at}`,status:x.active?"Publicada":"Inativa",image:x.cover_url}:{id:x.id,title:x.name,meta:`${x.city} · ${x.neighborhood}`,status:x.active?"Publicada":"Inativa",image:x.image_url}));setLoading(false)},[kind]);useEffect(()=>{load()},[load]);
async function remove(row:Row){if(!confirm(`Apagar “${row.title}”? Esta ação não pode ser desfeita.`))return;const t=sessionStorage.getItem("coopercica_admin_token");if(!t)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/cms_delete_content`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({p_kind:kind,p_id:row.id})});setMsg(r.ok?"Conteúdo apagado.":"Não foi possível apagar.");if(r.ok)load()}
async function clear(){if(!rows.length)return;if(!confirm(`Zerar ${title}? Isso apagará ${rows.length} item(ns) e não pode ser desfeito.`))return;if(!confirm("Confirma a exclusão de TODOS os conteúdos deste módulo?"))return;const t=sessionStorage.getItem("coopercica_admin_token");if(!t)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/cms_clear_content`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({p_kind:kind})});setMsg(r.ok?"Módulo zerado com sucesso.":"Não foi possível zerar. Essa ação é exclusiva para administradores.");if(r.ok)load()}
return <section className="cms-content-section"><div className="cms-content-heading"><div><span className="eyebrow">Conteúdo cadastrado</span><h2>{title}</h2></div><button className="cms-danger-outline" type="button" onClick={clear} disabled={!rows.length}>Zerar módulo</button></div>{msg?<div className="form-status"><strong>{msg}</strong></div>:null}{loading?<div className="cms-empty">Carregando conteúdos...</div>:rows.length?<div className="cms-content-list">{rows.map(row=><article className="cms-content-row" key={row.id}>{row.image?<img src={row.image} alt=""/>:<div className="cms-content-placeholder"/>}<div className="cms-content-info"><strong>{row.title}</strong><small>{row.meta}</small><span className="badge">{row.status}</span></div><button className="cms-delete-one" type="button" onClick={()=>remove(row)} aria-label={`Apagar ${row.title}`}>Apagar</button></article>)}</div>:<div className="cms-empty"><strong>Nenhum conteúdo cadastrado.</strong><span>Use o formulário abaixo para adicionar o primeiro item.</span></div>}</section>}