"use client";
import{FormEvent,useEffect,useState}from"react";import{SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL}from"@/lib/leaflets";import{LeafletMissingImages}from"./LeafletMissingImages";
type Kind="campaign"|"leaflet"|"magazine"|"store";type Data=Record<string,unknown>;
const fields:Record<Kind,Array<{name:string;label:string;type?:string}>>={campaign:[{name:"title",label:"Título"},{name:"sort_order",label:"Ordem",type:"number"},{name:"href",label:"Destino do banner"},{name:"background_color",label:"Cor de fundo"},{name:"starts_at",label:"Início da exibição",type:"datetime-local"},{name:"ends_at",label:"Fim da exibição",type:"datetime-local"}],magazine:[{name:"title",label:"Título"},{name:"edition",label:"Edição"},{name:"published_at",label:"Data da edição",type:"date"}],store:[{name:"store_number",label:"Número da unidade",type:"number"},{name:"name",label:"Nome"},{name:"slug",label:"Slug"},{name:"city",label:"Cidade"},{name:"neighborhood",label:"Bairro"},{name:"address",label:"Endereço"},{name:"phone",label:"Telefone"},{name:"hours",label:"Horário"},{name:"maps_url",label:"Link do Google Maps"}],leaflet:[{name:"name",label:"Nome do folheto"},{name:"starts_at",label:"Início da vigência",type:"date"},{name:"ends_at",label:"Fim da vigência",type:"date"}]};
const table:Record<Kind,string>={campaign:"site_campaigns",leaflet:"digital_leaflets",magazine:"site_magazines",store:"site_stores"};
const format=(v:unknown,type?:string)=>{if(v==null)return"";const s=String(v);return type==="datetime-local"?s.slice(0,16):s};
export function ContentEditor({kind,id,onDone}:{kind:Kind;id:string;onDone:()=>void}){const[data,setData]=useState<Data|null>(null),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
useEffect(()=>{const t=sessionStorage.getItem("coopercica_admin_token");if(!t)return;fetch(`${SUPABASE_URL}/rest/v1/rpc/cms_get_content`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({p_kind:kind,p_id:id})}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(setData).catch(()=>setMsg("Não foi possível carregar este conteúdo.")).finally(()=>setLoading(false))},[kind,id]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!data)return;const t=sessionStorage.getItem("coopercica_admin_token");if(!t)return;setSaving(true);setMsg("");const fd=new FormData(e.currentTarget);const body:Data={};for(const f of fields[kind])body[f.name]=f.type==="number"?Number(fd.get(f.name)):fd.get(f.name)||null;
if(kind==="campaign"){body.active=fd.get("active")==="on";body.target=fd.get("target");}
if(kind==="magazine")body.active=fd.get("active")==="on";
if(kind==="store"){body.active=fd.get("active")==="on";body.featured=fd.get("featured")==="on";body.services=String(fd.get("services")||"").split(",").map(x=>x.trim()).filter(Boolean)}
if(kind==="leaflet")body.status=fd.get("status");
const r=await fetch(`${SUPABASE_URL}/rest/v1/${table[kind]}?id=eq.${id}`,{method:"PATCH",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${t}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(body)});setSaving(false);if(r.ok){setMsg("Alterações salvas com sucesso.");setTimeout(onDone,450)}else setMsg("Não foi possível salvar as alterações.")}
if(loading)return <div className="cms-empty">Carregando conteúdo...</div>;if(!data)return <div className="form-status"><strong>{msg||"Conteúdo não encontrado."}</strong></div>;
return <form className="settings-form" onSubmit={submit}>{fields[kind].map(f=><label key={f.name}>{f.label}<input name={f.name} type={f.type||"text"} defaultValue={format(data[f.name],f.type)} required={["title","name","store_number","city","neighborhood","address","hours","starts_at","ends_at","published_at"].includes(f.name)}/></label>)}
{kind==="campaign"?<><label>Abrir em<select name="target" defaultValue={String(data.target||"_self")}><option value="_self">Mesma aba</option><option value="_blank">Nova aba</option></select></label><label><input name="active" type="checkbox" defaultChecked={Boolean(data.active)}/> Publicada</label></>:null}
{kind==="magazine"?<label><input name="active" type="checkbox" defaultChecked={Boolean(data.active)}/> Publicada</label>:null}
{kind==="store"?<><label className="form-span-full">Serviços<input name="services" defaultValue={Array.isArray(data.services)?data.services.join(", "):""}/><small>Separe por vírgula.</small></label><label><input name="featured" type="checkbox" defaultChecked={Boolean(data.featured)}/> Unidade em destaque</label><label><input name="active" type="checkbox" defaultChecked={Boolean(data.active)}/> Publicada</label></>:null}
{kind==="leaflet"?<label>Status<select name="status" defaultValue={String(data.status||"draft")}><option value="draft">Rascunho</option><option value="published">Publicado</option></select><small>Para substituir imagens ou a planilha de produtos, crie uma nova versão do folheto.</small></label>:null}
<div className="form-actions"><button className="button" disabled={saving}>{saving?"Salvando...":"Salvar alterações"}</button></div>{msg?<div className="form-status" role="status"><strong>{msg}</strong></div>:null}{kind==="leaflet"?<LeafletMissingImages leafletId={id}/>:null}</form>}