"use client";
import{DragEvent,useCallback,useEffect,useState}from"react";import{SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL}from"@/lib/leaflets";
type Missing={id:string;ean:string|null;description:string;complement:string|null;sort_order:number};
export function LeafletMissingImages({leafletId}:{leafletId:string}){const[items,setItems]=useState<Missing[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[msg,setMsg]=useState("");
const token=()=>sessionStorage.getItem("coopercica_admin_token")||"";
const load=useCallback(async()=>{setLoading(true);const r=await fetch(SUPABASE_URL+"/rest/v1/rpc/cms_leaflet_missing_images",{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:"Bearer "+token(),"Content-Type":"application/json"},body:JSON.stringify({p_leaflet_id:leafletId}),cache:"no-store"});if(r.ok)setItems(await r.json());setLoading(false)},[leafletId]);useEffect(()=>{load()},[load]);
async function upload(item:Missing,file?:File){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setMsg("Use JPG, PNG ou WebP.");return}if(file.size>10*1024*1024){setMsg("A imagem deve ter no máximo 10 MB.");return}setBusy(item.id);setMsg("");try{const ext=(file.name.split(".").pop()||"webp").toLowerCase();const path="products/manual/"+leafletId+"/"+(item.ean||item.id)+"-"+Date.now()+"."+ext;const up=await fetch(SUPABASE_URL+"/storage/v1/object/leaflet-assets/"+path,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:"Bearer "+token(),"Content-Type":file.type,"x-upsert":"false"},body:file});if(!up.ok)throw new Error(await up.text());const url=SUPABASE_URL+"/storage/v1/object/public/leaflet-assets/"+path;const save=await fetch(SUPABASE_URL+"/rest/v1/rpc/cms_set_leaflet_product_image",{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:"Bearer "+token(),"Content-Type":"application/json"},body:JSON.stringify({p_product_id:item.id,p_image_url:url})});if(!save.ok)throw new Error(await save.text());setItems(v=>v.filter(x=>x.id!==item.id));setMsg("Imagem de "+item.description+" adicionada.")}catch{setMsg("Não foi possível enviar esta imagem.")}finally{setBusy(null)}}
function drop(e:DragEvent<HTMLLabelElement>,item:Missing){e.preventDefault();upload(item,e.dataTransfer.files?.[0])}
if(loading)return <div className="cms-empty">Verificando imagens dos produtos...</div>;
return <section className="cms-missing-images"><div className="cms-missing-head"><div><span className="eyebrow">Imagens dos produtos</span><h2>{items.length?(items.length+" "+(items.length===1?"imagem pendente":"imagens pendentes")):"Banco de imagens completo"}</h2><p>{items.length?"Arraste a foto para o produto correspondente ou clique para escolher o arquivo.":"Todos os produtos deste folheto já possuem imagem."}</p></div></div>{msg?<div className="form-status" role="status"><strong>{msg}</strong></div>:null}{items.length?<div className="cms-missing-grid">{items.map(item=><article className="cms-missing-product" key={item.id}><div className="cms-missing-copy"><strong>{item.description}</strong>{item.complement?<span>{item.complement}</span>:null}<small>EAN {item.ean||"não informado"}</small></div><label className={"cms-image-drop "+(busy===item.id?"is-busy":"")} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,item)}><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy===item.id} onChange={e=>upload(item,e.target.files?.[0])}/><b>{busy===item.id?"Enviando...":"Arraste a imagem aqui"}</b><span>ou clique para selecionar · JPG/PNG/WebP · até 10 MB</span></label></article>)}</div>:null}</section>}