"use client";
import{ChangeEvent,useEffect,useState}from"react";import{SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL}from"@/lib/leaflets";
type Json=Record<string,string>;type Section={id:string;label:string;sort_order:number;active:boolean;content:Json};type Payload={settings:Record<string,Json>;sections:Section[]};
const labels:Record<string,string>={eyebrow:"Chamada superior",title1:"Título · linha 1",title2:"Título · linha 2",description:"Descrição",ctaLabel:"Texto do botão",ctaHref:"Destino do botão",image:"Imagem da seção"};
export function SiteCustomization(){const[data,setData]=useState<Payload|null>(null),[tab,setTab]=useState<"identity"|"sections">("identity"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
const token=()=>sessionStorage.getItem("coopercica_admin_token")||"";
useEffect(()=>{fetch(`${SUPABASE_URL}/rest/v1/rpc/cms_get_site_customization`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token()}`,"Content-Type":"application/json"},body:"{}"}).then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>setMsg("Não foi possível carregar a personalização."))},[]);
async function upload(file:File,folder:string){if(file.size>15*1024*1024)throw new Error("O arquivo excede 15 MB.");const path=`${folder}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/site-content/${path}`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token()}`,"Content-Type":file.type,"x-upsert":"false"},body:file});if(!r.ok)throw new Error("Falha no upload.");return `${SUPABASE_URL}/storage/v1/object/public/site-content/${path}`}
async function saveSetting(key:string,value:Json){const r=await fetch(`${SUPABASE_URL}/rest/v1/site_settings?key=eq.${key}`,{method:"PATCH",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token()}`,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({value,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await r.text());const rows=await r.json();if(!rows.length)throw new Error("A configuração não foi atualizada.")}
async function saveAll(){if(!data)return;setBusy(true);setMsg("");try{await Promise.all(Object.entries(data.settings).map(([k,v])=>saveSetting(k,v)));await Promise.all(data.sections.map(async s=>{const r=await fetch(`${SUPABASE_URL}/rest/v1/site_sections?id=eq.${s.id}`,{method:"PATCH",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token()}`,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({label:s.label,sort_order:s.sort_order,active:s.active,content:s.content,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await r.text());const rows=await r.json();if(!rows.length)throw new Error(`A seção ${s.label} não foi atualizada.`)}));setMsg("Personalização salva e publicada no site.")}catch{setMsg("Não foi possível salvar as alterações.")}finally{setBusy(false)}}
function setIdentity(k:string,v:string){if(!data)return;setData({...data,settings:{...data.settings,identity:{...data.settings.identity,[k]:v}}})}
function setSection(id:string,patch:Partial<Section>){if(!data)return;setData({...data,sections:data.sections.map(s=>s.id===id?{...s,...patch}:s)})}
async function media(e:ChangeEvent<HTMLInputElement>,target:"logo"|"logoWhite"|string){const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const url=await upload(file,target.startsWith("section:")?"sections":"identity");if(target.startsWith("section:")){const id=target.split(":")[1];const s=data?.sections.find(x=>x.id===id);if(s)setSection(id,{content:{...s.content,image:url}})}else setIdentity(target,url);setMsg("Arquivo enviado. Clique em Salvar alterações para publicar.")}catch(err){setMsg(err instanceof Error?err.message:"Falha no upload.")}finally{setBusy(false)}}
if(!data)return <div className="cms-empty">{msg||"Carregando personalização..."}</div>;const i=data.settings.identity||{};
return <section className="admin-page"><header className="admin-header"><div><span className="eyebrow">Site</span><h1>Personalização</h1><p>Edite identidade visual e conteúdo das seções sem alterar o código.</p></div><button className="button" onClick={saveAll} disabled={busy}>{busy?"Salvando...":"Salvar alterações"}</button></header><div className="cms-custom-tabs"><button data-active={tab==="identity"} onClick={()=>setTab("identity")}>Identidade visual</button><button data-active={tab==="sections"} onClick={()=>setTab("sections")}>Seções da Home</button></div>{msg?<div className="form-status"><strong>{msg}</strong></div>:null}
{tab==="identity"?<div className="settings-form"><label>Nome do site<input value={i.siteName||""} onChange={e=>setIdentity("siteName",e.target.value)}/></label><label>Cor principal<input type="color" value={i.primaryColor||"#1c4722"} onChange={e=>setIdentity("primaryColor",e.target.value)}/><small>Usada em títulos, navegação e elementos institucionais.</small></label><label>Cor secundária<input type="color" value={i.secondaryColor||"#6ab945"} onChange={e=>setIdentity("secondaryColor",e.target.value)}/></label><label>Cor de destaque<input type="color" value={i.accentColor||"#ef4037"} onChange={e=>setIdentity("accentColor",e.target.value)}/></label><label>Cor de fundo do site<input type="color" value={i.pageColor||"#f6faf6"} onChange={e=>setIdentity("pageColor",e.target.value)}/></label><label>URL do Delivery<input value={i.deliveryUrl||""} onChange={e=>setIdentity("deliveryUrl",e.target.value)}/></label><label>E-mail de atendimento<input type="email" value={i.contactEmail||""} onChange={e=>setIdentity("contactEmail",e.target.value)}/></label><label className="form-span-full">Logo principal<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>media(e,"logo")}/><small>Recomendado: arquivo horizontal com fundo transparente, mínimo 1200 px de largura. PNG, WebP ou SVG. Máximo: 15 MB.</small>{i.logo?<img className="cms-upload-preview" src={i.logo} alt="Logo atual"/>:null}</label><label className="form-span-full">Logo para fundos escuros<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>media(e,"logoWhite")}/><small>Mesmas proporções do logo principal. PNG, WebP ou SVG. Máximo: 15 MB.</small>{i.logoWhite?<img className="cms-upload-preview cms-upload-preview-dark" src={i.logoWhite} alt="Logo claro atual"/>:null}</label></div>:<div className="cms-section-editor">{data.sections.map(s=><article className="cms-section-card" key={s.id}><div className="cms-section-card-head"><div><small>Seção da Home</small><h2>{s.label}</h2></div><label className="cms-switch"><input type="checkbox" checked={s.active} onChange={e=>setSection(s.id,{active:e.target.checked})}/> Exibir</label></div><div className="settings-form">{Object.entries(s.content).filter(([k])=>k!=="image").map(([k,v])=><label key={k}>{labels[k]||k}<input value={v||""} onChange={e=>setSection(s.id,{content:{...s.content,[k]:e.target.value}})}/></label>)}{"image" in s.content?<label className="form-span-full">Imagem da seção<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>media(e,`section:${s.id}`)}/><small>Recomendado: 1600 × 1000 px, JPG/PNG/WebP. Máximo: 15 MB.</small>{s.content.image?<img className="cms-upload-preview" src={s.content.image} alt="Imagem atual"/>:null}</label>:null}</div></article>)}</div>}</section>}